import type { AiModel, Camera, HardwareTelemetry, ModelCategory, Role, Severity } from './types'

export const SITE_NAME = 'Sahil-e-Baseera — AI COMMAND & CONTROL CENTER'
export const SITE_SHORT = 'Sahil-e-Baseera'
export const SITE_TAGLINE = 'TRAFFIC SAFETY MONITOR'
export const DEFAULT_IP_PREFIX = '192.168.27'

export const DUTY_OFFICER = {
  name: 'Muhammad Ammar',
  role: 'Duty Security Officer',
  phone: '+923494533107',
  whatsapp: '923494533107',
}

export const STORAGE_KEYS = {
  incidents: 'safecity.incidents.v2',
  firedEvents: 'safecity.firedEvents.v2',
  severityOverrides: 'safecity.severityOverrides.v2',
  cameraPins: 'safecity.cameraPins.v2',
  cameraVideoUrl: 'safecity.cameraVideoUrl.v2',
  mapImage: 'safecity.mapImage.v2',
  cameras: 'safecity.cameras.v2',
  cameraSequence: 'safecity.cameraSequence.v2',
  theme: 'safecity.theme.v2',
} as const

export const ROLE_LABELS: Record<Role, string> = {
  'super-admin': 'System Administrator',
  operator: 'Control Room Operator',
  guard: 'Security Guard (View-Only)',
}

export const SEVERITY_META: Record<
  Severity,
  { label: string; color: string; ring: string; text: string; dot: string; badge: string }
> = {
  high: {
    label: 'CRITICAL',
    color: '#F43F5E',
    ring: 'ring-danger/60',
    text: 'text-danger',
    dot: 'bg-danger',
    badge: 'border-danger/50 bg-danger/15 text-danger',
  },
  medium: {
    label: 'WARNING',
    color: '#F59E0B',
    ring: 'ring-warn/60',
    text: 'text-warn',
    dot: 'bg-warn',
    badge: 'border-warn/50 bg-warn/15 text-warn',
  },
  low: {
    label: 'ADVISORY',
    color: '#38BDF8',
    ring: 'ring-info/50',
    text: 'text-info',
    dot: 'bg-info',
    badge: 'border-info/50 bg-info/15 text-info',
  },
}

export const CATEGORY_META: Record<
  ModelCategory,
  { title: string; subtitle: string; color: string; badge: string; border: string; bg: string }
> = {
  traffic: {
    title: 'Traffic & Vehicle Monitoring',
    subtitle: 'Corridor enforcement, ANPR, radar speed, and parking control',
    color: '#0EA5E9',
    badge: 'bg-cyan-500/15 text-cyan-400 border-cyan-500/30',
    border: 'border-cyan-500/30',
    bg: 'from-cyan-500/10 to-transparent',
  },
  behaviour: {
    title: 'Person Behaviour & Security',
    subtitle: 'Crowd density analysis, perimeter wall breach, and fall detection',
    color: '#F59E0B',
    badge: 'bg-amber-500/15 text-amber-400 border-amber-500/30',
    border: 'border-amber-500/30',
    bg: 'from-amber-500/10 to-transparent',
  },
  safety: {
    title: 'Critical Safety & Emergency',
    subtitle: 'Rapid hazard response: early fire, smoke plume, and crash detection',
    color: '#EF4444',
    badge: 'bg-rose-500/15 text-rose-400 border-rose-500/30',
    border: 'border-rose-500/30',
    bg: 'from-rose-500/10 to-transparent',
  },
  tracking: {
    title: 'Multi-Camera Tracking',
    subtitle: 'Canonical Re-ID cross-camera trajectory reconstruction for persons and vehicles',
    color: '#A855F7',
    badge: 'bg-purple-500/15 text-purple-400 border-purple-500/30',
    border: 'border-purple-500/30',
    bg: 'from-purple-500/10 to-transparent',
  },
}

export const AI_MODELS: AiModel[] = [
  // 1. Traffic
  {
    id: 'helmet',
    name: 'Helmet Violation Detection',
    short: 'HELMET',
    category: 'traffic',
    severity: 'medium',
    description: 'Tracks motorcyclists via ByteTrack and detects riders without certified safety helmets.',
    capturesList: [
      'Unhelmeted rider face/head crop',
      'Motorcycle license plate link',
      'Compliance percentage gauge',
      'ByteTrack 90-frame occlusion Re-ID',
    ],
    liveActiveDetections: 14,
    avgConfidence: 93.4,
    captureTelemetry: [
      {
        timestamp: '14:32:05',
        cameraName: 'CAM-05 Checkpoint Gate V',
        confidence: 96.2,
        summary: 'Biker without helmet on Honda CD-70',
        hasHelmet: false,
        bikePlate: 'RWP-9918',
        vehicleColor: 'Red',
      },
      {
        timestamp: '14:28:40',
        cameraName: 'CAM-05 Checkpoint Gate V',
        confidence: 91.8,
        summary: 'Pillion passenger helmet missing',
        hasHelmet: false,
        bikePlate: 'ISB-4412',
        vehicleColor: 'Black',
      },
    ],
  },
  {
    id: 'anpr',
    name: 'Vehicle ANPR & Profiling',
    short: 'ANPR / VMMR',
    category: 'traffic',
    severity: 'low',
    description: 'High-speed license plate OCR combined with OpenAI CLIP vehicle color and ConvNeXt make/model identification.',
    capturesList: [
      'License plate alphanumeric OCR (fast-plate-ocr)',
      '12-Class OpenAI CLIP vehicle color classification',
      'ConvNeXt make and model recognition (397 classes)',
      'Traffic lane tracking and entry timestamp',
    ],
    liveActiveDetections: 148,
    avgConfidence: 97.1,
    captureTelemetry: [
      {
        timestamp: '14:33:12',
        cameraName: 'CAM-01 Main Boulevard Gate 1',
        confidence: 98.4,
        summary: 'Silver Honda Civic [CUS-4005]',
        plate: 'CUS-4005',
        plateConfidence: 98.4,
        vehicleColor: 'Silver',
        vehicleMake: 'Honda Civic',
      },
      {
        timestamp: '14:31:55',
        cameraName: 'CAM-06 Market Road Block E',
        confidence: 96.7,
        summary: 'White Toyota Corolla [ISB-7821]',
        plate: 'ISB-7821',
        plateConfidence: 96.7,
        vehicleColor: 'White',
        vehicleMake: 'Toyota Corolla',
      },
    ],
  },
  {
    id: 'wrongway',
    name: 'Wrong-Way Detection',
    short: 'WRONG-WAY',
    category: 'traffic',
    severity: 'high',
    description: 'Monitors directional velocity vectors against pre-calibrated corridor flow angles to flag reverse driving.',
    capturesList: [
      'Reverse travel vector & angle deviation (>120 deg)',
      'Corridor lane designation check',
      'Reverse travel distance meter',
      'Vehicle snapshot with red direction arrow HUD',
    ],
    liveActiveDetections: 3,
    avgConfidence: 95.8,
    captureTelemetry: [
      {
        timestamp: '14:25:10',
        cameraName: 'CAM-08 One-Way Service Rd',
        confidence: 96.4,
        summary: 'Vehicle traveling opposite to designated corridor flow',
        reverseHeadingDegrees: 174,
        speedKmh: 34.2,
        vehicleColor: 'Grey',
        vehicleMake: 'Suzuki Swift',
      },
    ],
  },
  {
    id: 'speed',
    name: 'Speed Estimation & Radar',
    short: 'SPEED RADAR',
    category: 'traffic',
    severity: 'medium',
    description: 'Planar homography pixel-to-meter coordinate transformation calculating true ground speed with overspeed alerts.',
    capturesList: [
      'Real-world speed measurement (km/h)',
      'Configurable corridor speed limit slider (20-120 km/h)',
      'Delta overspeed calculator (+km/h)',
      'Sub-pixel trajectory smoothing and distance tracked',
    ],
    liveActiveDetections: 22,
    avgConfidence: 94.6,
    captureTelemetry: [
      {
        timestamp: '14:32:48',
        cameraName: 'CAM-06 Market Road Block E',
        confidence: 95.2,
        summary: 'Vehicle @ 68.4 km/h in 40 km/h corridor zone',
        speedKmh: 68.4,
        speedLimitKmh: 40.0,
        deltaSpeedKmh: 28.4,
        trackedDistanceM: 42.1,
        plate: 'JW-4451',
      },
      {
        timestamp: '14:30:15',
        cameraName: 'CAM-01 Main Boulevard Gate 1',
        confidence: 93.9,
        summary: 'Vehicle @ 74.1 km/h in 50 km/h corridor zone',
        speedKmh: 74.1,
        speedLimitKmh: 50.0,
        deltaSpeedKmh: 24.1,
        trackedDistanceM: 58.6,
        plate: 'LEE-309',
      },
    ],
  },
  {
    id: 'parking',
    name: 'Idle / Illegal Vehicle Parking',
    short: 'ILLEGAL PARKING',
    category: 'traffic',
    severity: 'low',
    description: 'Perimeter dwell-time analyzer flagging stationary vehicles inside no-stopping zones and yellow/red curb areas.',
    capturesList: [
      'Stationary vehicle dwell stopwatch (seconds/minutes)',
      'Restricted red-curb / emergency corridor boundary',
      'Target vehicle license plate association',
      'Tow/dispatch alert countdown',
    ],
    liveActiveDetections: 5,
    avgConfidence: 96.0,
    captureTelemetry: [
      {
        timestamp: '14:20:00',
        cameraName: 'CAM-02 Jamia Mosque Rd',
        confidence: 97.3,
        summary: 'Vehicle parked in emergency gate corridor for >14 mins',
        parkingDurationSec: 865,
        noParkingZone: 'Emergency Corridor Red-Curb',
        plate: 'FD-1092',
        vehicleColor: 'White',
      },
    ],
  },

  // 2. Person Behaviour
  {
    id: 'falling',
    name: 'Falling Person Detection',
    short: 'FALL DETECTION',
    category: 'behaviour',
    severity: 'high',
    description: 'Pose estimation and bounding-box aspect ratio analyzer detecting rapid vertical drops of elderly or medically distressed pedestrians.',
    capturesList: [
      'Vertical centroid velocity drop rate',
      'Post-fall horizontal bounding box aspect ratio (W > 1.8 * H)',
      'Stationary post-impact timer for medical distress',
      'Immediate alert dispatch to nearest patrol guard',
    ],
    liveActiveDetections: 1,
    avgConfidence: 93.7,
    captureTelemetry: [
      {
        timestamp: '14:18:22',
        cameraName: 'CAM-03 Sector B Community Park',
        confidence: 94.1,
        summary: 'Pedestrian fall detected near park walkway bench',
        fallPostureStatus: 'Horizontal Posture (No Recovery > 15s)',
        medicalPriority: 'URGENT',
      },
    ],
  },
  {
    id: 'mob',
    name: 'Mob / Crowd Gathering (>7 Persons)',
    short: 'MOB GATHERING',
    category: 'behaviour',
    severity: 'medium',
    description: 'Density cluster head-counter that detects anomalous localized gatherings exceeding safety thresholds (>7 persons).',
    capturesList: [
      'Real-time head / pedestrian cluster count',
      'Configurable crowd threshold (Trigger: >7 persons in 15m radius)',
      'Crowd density dispersion vector',
      'Fight / altercation risk probability score',
    ],
    liveActiveDetections: 2,
    avgConfidence: 91.5,
    captureTelemetry: [
      {
        timestamp: '14:26:05',
        cameraName: 'CAM-07 School Gate Block H',
        confidence: 92.4,
        summary: 'Crowd cluster of 11 persons formed outside gate',
        crowdCount: 11,
        crowdThreshold: 7,
      },
    ],
  },
  {
    id: 'wallbreach',
    name: 'Wall Breach Detection',
    short: 'WALL BREACH',
    category: 'behaviour',
    severity: 'high',
    description: 'Perimeter boundary intrusion detection monitoring society boundary walls and restricted security fences.',
    capturesList: [
      'Virtual tripwire crossing on perimeter wall edge',
      'Climbing / scaling trajectory analysis',
      'Restricted zone invasion bounding box',
      'Perimeter sector alert coordinates',
    ],
    liveActiveDetections: 1,
    avgConfidence: 95.2,
    captureTelemetry: [
      {
        timestamp: '14:15:30',
        cameraName: 'CAM-04 Sector C Perimeter Fence',
        confidence: 95.8,
        summary: 'Intrusion flagged across North-East boundary wall',
        wallBreachZone: 'Sector C Perimeter Fence (North-East)',
        intrusionVector: 'External Scaling -> Interior Ground',
      },
    ],
  },

  // 3. Critical Safety
  {
    id: 'fire',
    name: 'Smoke & Fire Detection',
    short: 'FIRE & SMOKE',
    category: 'safety',
    severity: 'high',
    description: 'Dual-spectral flame luminescence and smoke plume volumetric expansion detector for early hazard containment.',
    capturesList: [
      'Flame luminescence and flicker frequency analysis',
      'Expanding smoke plume opacity calculation',
      'Early-stage roof and brush fire detection',
      'Automatic high-priority siren audio trigger',
    ],
    liveActiveDetections: 1,
    avgConfidence: 96.1,
    captureTelemetry: [
      {
        timestamp: '14:31:02',
        cameraName: 'CAM-02 Jamia Mosque Rd',
        confidence: 96.8,
        summary: 'Dense smoke plume and flame signature on rooftop',
        smokeDensityPct: 82.4,
        fireLuminescence: 'High Intensity (Flicker 14Hz)',
      },
    ],
  },
  {
    id: 'accident',
    name: 'Accident / Crash Detection',
    short: 'CRASH DETECTION',
    category: 'safety',
    severity: 'high',
    description: 'Deep learning collision detector recognizing rapid kinetic energy dissipation, vehicle deformation, and abnormal vehicle overlaps.',
    capturesList: [
      'Sudden deceleration anomaly detection',
      'Inter-vehicle IoU collision overlap tracking',
      'Severity level categorization (CRITICAL / MODERATE)',
      'Freeze-frame evidence capture for emergency services',
    ],
    liveActiveDetections: 2,
    avgConfidence: 94.3,
    captureTelemetry: [
      {
        timestamp: '14:29:14',
        cameraName: 'CAM-04 Sector C Junction',
        confidence: 94.7,
        summary: 'Two-vehicle collision at Sector C main intersection',
        accidentSeverity: 'CRITICAL',
      },
    ],
  },

  // 4. Multi Camera Tracking
  {
    id: 'track_person',
    name: 'Multi-Camera Person Tracking',
    short: 'RE-ID PERSON',
    category: 'tracking',
    severity: 'low',
    description: 'Cross-camera Canonical Re-ID matching pedestrian visual embeddings to reconstruct individual walking routes across nodes.',
    capturesList: [
      '512-D deep feature visual embedding (clothing, posture, gait)',
      'Cross-camera timeline matching and node handoff',
      'Chronological map route reconstruction',
      'Suspect search by description or snapshot query',
    ],
    liveActiveDetections: 36,
    avgConfidence: 92.8,
    captureTelemetry: [
      {
        timestamp: '14:30:50',
        cameraName: 'CAM-03 Sector B Community Park',
        confidence: 93.5,
        summary: 'Track #104 [Navy Jacket, Dark Jeans] handed off from CAM-01',
        reidTrackId: 'PID-104',
        trajectoryHandoff: ['CAM-01 Gate 1 (14:15)', 'CAM-02 Mosque Rd (14:22)', 'CAM-03 Park (14:30)'],
      },
    ],
  },
  {
    id: 'track_vehicle',
    name: 'Multi-Camera Vehicle Tracking',
    short: 'RE-ID VEHICLE',
    category: 'tracking',
    severity: 'low',
    description: 'Synchronizes license plate recognition with vehicle color, make, and body profile to track vehicle movements across society gates.',
    capturesList: [
      'Plate + vehicle color/model biometric pairing',
      'Entry-to-exit corridor duration and speed profile',
      'Cross-gate journey mapping with pinpoint timestamps',
      'Missing or cloned plate anomaly detection',
    ],
    liveActiveDetections: 68,
    avgConfidence: 95.4,
    captureTelemetry: [
      {
        timestamp: '14:32:10',
        cameraName: 'CAM-06 Market Road Block E',
        confidence: 96.1,
        summary: 'Vehicle #42 [Silver Honda Civic CUS-4005] moving east',
        reidTrackId: 'VID-42',
        trajectoryHandoff: ['CAM-01 Gate 1 (14:20)', 'CAM-04 Sector C (14:26)', 'CAM-06 Market Rd (14:32)'],
      },
    ],
  },
]

const V = (name: string) => `/videos/${name}`

export const CAMERAS: Camera[] = [
  {
    id: 'CAM-01',
    index: 1,
    name: 'Main Boulevard Gate 1',
    zone: 'Gate-I Jinnah',
    ip: '192.168.27.101',
    videoUrl: V('anpr_.mp4'),
    duration: 20,
    models: ['anpr', 'speed', 'track_vehicle'],
    x: 44,
    y: 4,
    events: [
      {
        time: 4,
        modelId: 'anpr',
        title: 'Vehicle Plate Identified',
        detail: 'Silver Honda Civic [CUS-4005] scanned at Gate 1 inbound lane',
        confidence: 98.4,
        plate: 'CUS-4005',
        vehicle: 'Silver Honda Civic',
      },
      {
        time: 12,
        modelId: 'speed',
        title: 'Speed Advisory',
        detail: 'Vehicle at 54 km/h in 50 km/h sector zone',
        confidence: 93.9,
        speed: 54,
        plate: 'LEE-309',
        vehicle: 'Toyota Corolla',
      },
    ],
  },
  {
    id: 'CAM-02',
    index: 2,
    name: 'Sector A — Jamia Mosque Rd',
    zone: 'Block A',
    ip: '192.168.27.102',
    videoUrl: V('fire_and_smoke.mp4'),
    duration: 12,
    models: ['fire', 'parking'],
    x: 13,
    y: 16,
    events: [
      {
        time: 1,
        modelId: 'fire',
        title: 'Fire & Smoke Detected',
        detail: 'Active smoke plume and thermal signature on rooftop',
        confidence: 96.8,
      },
      {
        time: 7,
        modelId: 'parking',
        title: 'Illegal Parking in Corridor',
        detail: 'White Toyota stationary in emergency red curb lane for >10 mins',
        confidence: 95.0,
        plate: 'FD-1092',
        vehicle: 'Toyota Yaris',
      },
    ],
  },
  {
    id: 'CAM-03',
    index: 3,
    name: 'Sector B — Community Park',
    zone: 'Block B / Roundabout',
    ip: '192.168.27.103',
    videoUrl: V('weapon(1)_.mp4'),
    duration: 10,
    models: ['falling', 'track_person'],
    x: 26,
    y: 19,
    events: [
      {
        time: 2,
        modelId: 'falling',
        title: 'Falling Person Alert',
        detail: 'Rapid vertical descent detected near park walkway; horizontal posture verified',
        confidence: 94.1,
      },
      {
        time: 6,
        modelId: 'track_person',
        title: 'Cross-Camera Re-ID Match',
        detail: 'Person PID-104 recognized moving towards Block B roundabout',
        confidence: 93.5,
      },
    ],
  },
  {
    id: 'CAM-04',
    index: 4,
    name: 'Service Rd — Sector C Junction',
    zone: 'Block D',
    ip: '192.168.27.104',
    videoUrl: V('accident.mp4'),
    duration: 14,
    models: ['accident', 'wallbreach'],
    x: 46,
    y: 22,
    events: [
      {
        time: 3,
        modelId: 'accident',
        title: 'Road Accident Detected',
        detail: 'High-energy vehicle collision at Sector C cross-junction',
        confidence: 94.7,
      },
      {
        time: 9,
        modelId: 'wallbreach',
        title: 'Perimeter Wall Intrusion',
        detail: 'Boundary scaling event flagged at North-East perimeter wall segment',
        confidence: 95.8,
      },
    ],
  },
  {
    id: 'CAM-05',
    index: 5,
    name: 'Security Checkpoint — Gate V Nishtar',
    zone: 'Gate-V Nishtar',
    ip: '192.168.27.105',
    videoUrl: V('helmet_violation(1)_.mp4'),
    duration: 18,
    models: ['helmet', 'anpr'],
    x: 15,
    y: 40,
    events: [
      {
        time: 3,
        modelId: 'helmet',
        title: 'Helmet Violation Detected',
        detail: 'Motorcyclist without helmet flagged at checkpoint inbound barrier',
        confidence: 96.2,
        plate: 'RWP-9918',
        vehicle: 'Honda CD-70 — Red',
      },
      {
        time: 13,
        modelId: 'helmet',
        title: 'Helmet Violation Detected',
        detail: 'Second rider without helmet moving past barrier lane',
        confidence: 91.8,
        plate: 'RWP-2231',
        vehicle: 'Suzuki GS-150 — Blue',
      },
    ],
  },
  {
    id: 'CAM-06',
    index: 6,
    name: 'Market Road — Block E',
    zone: 'Block E',
    ip: '192.168.27.106',
    videoUrl: V('speed_estimation_.mp4'),
    duration: 15,
    models: ['speed', 'anpr', 'track_vehicle'],
    x: 14,
    y: 30,
    events: [
      {
        time: 3,
        modelId: 'speed',
        title: 'Over-speeding Violation',
        detail: 'Vehicle clocked @ 68.4 km/h in 40 km/h market corridor zone',
        confidence: 95.2,
        plate: 'JW-4451',
        vehicle: 'Honda Civic — Silver',
        speed: 68.4,
      },
    ],
  },
  {
    id: 'CAM-07',
    index: 7,
    name: 'School Gate — Block H Master Plan',
    zone: 'Block H',
    ip: '192.168.27.107',
    videoUrl: V('fight_detection_output.mp4'),
    duration: 12,
    models: ['mob', 'track_person'],
    x: 77,
    y: 58,
    events: [
      {
        time: 3,
        modelId: 'mob',
        title: 'Mob Gathering (>7 Persons)',
        detail: 'Cluster of 11 persons assembled outside school perimeter',
        confidence: 92.4,
        crowdCount: 11,
      },
    ],
  },
  {
    id: 'CAM-08',
    index: 8,
    name: 'Corridor Exit — Block K Commercial',
    zone: 'Block K',
    ip: '192.168.27.108',
    videoUrl: V('wrongway.mp4'),
    duration: 14,
    models: ['wrongway', 'parking'],
    x: 62,
    y: 72,
    events: [
      {
        time: 4,
        modelId: 'wrongway',
        title: 'Wrong-Way Vehicle Alert',
        detail: 'Vehicle traveling opposite to designated one-way exit lane',
        confidence: 96.4,
        speed: 34.2,
      },
    ],
  },
]

export const INITIAL_HARDWARE_SPECS: HardwareTelemetry = {
  cpu: {
    model: 'AMD Ryzen 9 6900HS (8 Cores, 16 Threads)',
    percent: 28.4,
    cores: 8,
  },
  gpu: {
    model: 'NVIDIA GeForce RTX 3050 Laptop GPU (CUDA 12.1)',
    utilPercent: 62.1,
    vramUsedMb: 3120,
    vramTotalMb: 4096,
    tempC: 58,
    cudaActive: true,
  },
  ram: {
    usedGb: 18.2,
    totalGb: 32.0,
    percent: 56.8,
  },
  storage: {
    usedGb: 412.5,
    totalGb: 1000.0,
    percent: 41.2,
  },
  fps: 58.4,
}

export const EXTRA_VIDEOS: { label: string; url: string }[] = [
  { label: 'Wrong-way Driving', url: V('wrongway.mp4') },
  { label: 'Underage Driver', url: V('underage(1).mp4') },
  { label: 'Accident (alt)', url: V('accident_detection_output.mp4') },
  { label: 'Fire & Smoke (alt)', url: V('fire_and_smoke(1)_.mp4') },
  { label: 'Helmet (raw)', url: V('helmet_violation_detection_raw.mp4') },
  { label: 'Helmet (alt)', url: V('helmet_violation.mp4') },
]

export const CAMERA_SOURCE_VIDEOS: { label: string; url: string; duration: number }[] = [
  ...CAMERAS.map((c) => ({ label: `${c.name} (CAM ${c.index})`, url: c.videoUrl, duration: c.duration })),
  ...EXTRA_VIDEOS.map((v) => ({ label: v.label, url: v.url, duration: 12 })),
]
